# Generated by Django 3.1.4 on 2021-01-05 18:36

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_currency', djmoney.models.fields.CurrencyField(choices=[('BOB', 'Peso boliviano'), ('USD', 'US Dollar')], default=None, editable=False, max_length=3, null=True)),
                ('money', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
